#!/usr/bin/bash

# Configuration for sbatch

#SBATCH -J  sp               # job name
#SBATCH -o  sp.%j.out        # name of stdout output file (%j expands to %jobId)
#_SBATCH -e  sp.%j.err       # (optional) name of stderr file. If it's not specified, stadout(-o) includes stderr.
#SBATCH -t 3-00:00:00        # run time (d-hh:mm:ss) - day/hour/minute/second

#### Resource
#SBATCH -p 2080ti            # queue name or partiton
#SBATCH --gres=gpu:1         # gpus per node
#_SBATCH -q nogpu
#SBATCH --cpus-per-task=1

##  node
#_SBATCH --nodelist=n14
#SBATCH --nodes=1            # number of nodes 
#SBATCH --ntasks-per-node=1


# Note
#
# The above cofnig uses 1 gpu and 1 cpu

# Add the following source and conda commands in your bash script,
# which are represented as arguments "$@"
#
# source $(conda info --base)/etc/profile.d/conda.sh  # if it's not working, use the real path instead
# conda activate some-env

srun "$@"
